### ISSUE TITLE
Strange issue with knife opc dbcs list

### ISSUE THREAD

**Issue by lfeldman** [mccoold/knife-oracle_public_cloud#5]
Hi,

Today I have installed your gem plugin and I was trying just to list the DBCS instances with the command knife opc dbcs list. According to the docs I have provided username (-u), OPC domain id (-I) and password (-p). As a result I have received the error message:
ERROR: Argument error: wrong number of arguments (3 of 4).

I have no idea what fourth argument I should deliver. It is not documented. I could add I had created knife.rb file with all the necessary lines within. 

Best,

Luke

**Comment by mccoold** [comment]
Luke,

can you please run gemlist from your ruby install path that you are leveraging for Chef.  I think you have an older version of one of the gems it is dependent on.  If so the fix would be to run gem update

**Comment by lfeldman** [comment]
Hi Daryn,

Gem update has fixed the issue. Thanks a lot!

Best,

Luke

**Comment by mccoold** [comment]
no problem any other questions or enhancement requests let me know.

Thank You,

Daryn McCool
