### ISSUE TITLE
knife opc dbcs and jcs commands are returning error code 401 

### ISSUE THREAD

**Issue by bageorge** [mccoold/knife-oracle_public_cloud#6]
When I run any dbcs or jcs commands (even the simplest list command), 401 error is returned instead of expected values. I have stored my credentials and rest api end point in a file called knife.rb and executed the command as "knife opc dbcs list" or "knife opc jcs list" as the case maybe. But every time the command returns the follow error message.

error, JSON was not returned  the http response code was401

Please help me.

**Comment by mccoold** [comment]
based on your other issue I assume you got past this?

Thank You,
Daryn McCool

**Comment by bageorge** [comment]
Hi Daryn,
The issue is not resolved yet, though  other issue was resolved this still persist. I have used many userid/password/rest api combinations but all of them ended the same error. Do we require any authorize token like in REST API cookie to connect and get the details? 
Thanks
Babu

**Comment by mccoold** [comment]
resolved in version 0.1.6
