### ISSUE TITLE
error in jcs.rb file

### ISSUE THREAD

**Issue by bageorge** [mccoold/knife-oracle_public_cloud#7]
When I run the command "knife opc jcs <commands>", I got the following error

[root@tooling-instance bin]# knife opc jcs list -p Simple5U -VV
Ignoring unf_ext-0.0.7.2 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.2
INFO: Using configuration from /opt/chefdk/embedded/bin/knife.rb
error, JSON was not returned  the http response code was401
/root/.chefdk/gem/ruby/2.1.0/gems/knife-oracle_public_cloud-0.1.5/lib/chef/knife/jcs.rb:76:in `run': undefined method`put' for #Chef::Knife::OpcJcsList:0x00000002e29738 (NoMethodError)
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/local_mode.rb:44:in`with_server_connectivity'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/knife.rb:219:in`run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/knife.rb:156:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/bin/knife:25:in`<top (required)>'
        from /opt/chefdk/embedded/bin/knife:22:in `load'
        from /opt/chefdk/embedded/bin/knife:22:in`<main>'

When I checked the source code jcs.rb, at line number 76 it was "put" instead of "puts". I changed the code to puts and run the command, and the error is gone.

Is this correct? If so, how the source code can be corrected so that the plugin will not throw this error anymore. Please advise.

**Comment by mccoold** [comment]
thank you for raising this issue, I will look at the source and publish a corrected version of the gem as soon as I can

Thank You,

Daryn McCool

**Comment by mccoold** [comment]
this is resolved in the 0.1.6
